use humanfriends;
drop table actions;
drop table hamsters;
drop table dogs;
drop table cats;
drop table pets;
drop table packanimals;
drop table animals;
drop table table_list;
drop table camels;
drop table donkeys;
drop table horses;
drop table animals_all;
select * from animals_all;
select * from animals;
drop table cat_actions;
drop table dog_actions;
drop table horse_actions;
drop table hamster_actions;
drop table camels_actions;
drop table donkey_actions;
alter table dogs drop column id_actions;
